import { readFileSync, writeFileSync, readdirSync, copyFileSync, mkdirSync, existsSync } from 'fs';
import { join, basename } from 'path';

const GAS_SRC = './gas-src';
const DIST_GAS = './dist-gas';
const SETUP_FILE = '00-setup.gs';

try {
  mkdirSync(DIST_GAS, { recursive: true });

  if (existsSync(join(GAS_SRC, SETUP_FILE))) {
    copyFileSync(join(GAS_SRC, SETUP_FILE), join(DIST_GAS, 'setup.gs'));
    console.log('✓ setup.gs copied directly');
  }

  const files = [];

  if (existsSync(GAS_SRC)) {
    readdirSync(GAS_SRC)
      .filter(f => f.endsWith('.gs') && f !== SETUP_FILE)
      .sort()
      .forEach(f => files.push(join(GAS_SRC, f)));

    const modulesDir = join(GAS_SRC, 'modules');
    if (existsSync(modulesDir)) {
      readdirSync(modulesDir)
        .filter(f => f.endsWith('.gs'))
        .sort()
        .forEach(f => files.push(join(modulesDir, f)));
    }
  }

  let output = '// ==== AUTO-GENERATED BY COMPILER scripts/build-gas.mjs ====\n';
  output += '// DO NOT EDIT THIS FILE MANUALLY — edit gas-src/ files instead\n';
  output += `// Compiled Date: ${new Date().toISOString()}\n\n`;

  for (const filePath of files) {
    const content = readFileSync(filePath, 'utf-8');
    const name = basename(filePath);
    output += `\n// ==========================================\n`;
    output += `// SOURCE COMPONENT: ${name}\n`;
    output += `// ==========================================\n\n`;
    output += content;
    output += '\n';
  }

  writeFileSync(join(DIST_GAS, 'code.gs'), output);
  console.log(`✓ code.gs successfully compiled from ${files.length} modules inside /dist-gas`);

  const appsscriptJsonSrc = join(GAS_SRC, 'appsscript.json');
  if (existsSync(appsscriptJsonSrc)) {
    copyFileSync(appsscriptJsonSrc, join(DIST_GAS, 'appsscript.json'));
    console.log('✓ appsscript.json copied to dist-gas');
  } else {
    const config = {
      timeZone: "Asia/Jakarta",
      dependencies: {},
      exceptionLogging: "STACKDRIVER",
      runtimeVersion: "V8",
      webapp: {
        access: "ANYONE",
        executeAs: "USER_DEPLOYING"
      }
    };
    writeFileSync(join(DIST_GAS, 'appsscript.json'), JSON.stringify(config, null, 2), 'utf8');
    console.log('✓ Default appsscript.json created in dist-gas');
  }

  try {
    if (existsSync('./dist/index.html')) {
      const htmlRaw = readFileSync('./dist/index.html', 'utf-8');
      const { minify } = await import('html-minifier-terser');
      const minifiedHtml = await minify(htmlRaw, {
        collapseWhitespace: true,
        removeComments: true,
        minifyCSS: true,
        minifyJS: true,
        removeAttributeQuotes: false
      });
      writeFileSync(join(DIST_GAS, 'webapp.html'), minifiedHtml, 'utf-8');
      const rawKb = (Buffer.byteLength(htmlRaw, 'utf-8') / 1024).toFixed(2);
      const minKb = (Buffer.byteLength(minifiedHtml, 'utf-8') / 1024).toFixed(2);
      console.log(`✓ webapp.html minified & copied to dist-gas (${rawKb} KB -> ${minKb} KB)`);
    } else {
      console.log('ℹ️ ./dist/index.html not found yet. Run npm run build first before compiling webapp.html.');
    }
  } catch (err) {
    console.warn('⚠️ webapp.html copy skipped/failed:', err.message);
  }

} catch (err) {
  console.error('✗ Build GAS compiler failed:', err.message);
  process.exit(1);
}
